export const LOAD_COMPANIES = "LOAD_COMPANIES";
export const SUCCESS_COMPANIES = "SUCCESS_COMPANIES";
export const FAIL_COMPANIES = "FAIL_COMPANIES";
export const GET_COMPANY= "GET_COMPANY";

export const LOAD_JOB_OFFERS = "LOAD_JOB_OFFERS";
export const SUCCESS_JOB_OFFERS = "SUCCESS_JOB_OFFERS";
export const FAIL_JOB_OFFERS = "FAIL_JOB_OFFERS";
export const GET_JOB_OFFER = "GET_JOB_OFFER";

export const LOAD_RECRUITERS = "LOAD_RECRUITERS";
export const SUCCESS_RECRUITERS = "SUCCESS_RECRUITERS";
export const FAIL_RECRUITERS = "FAIL_RECRUITERS";
